version: '3.5'
services:
 zbx-prx-mysql:
  #image: zabbix/zabbix-proxy-mysql:ol-6.0.21
  #image: zbx-prx-mysql-odbc:v1
  image: douglasportugal/zbx-custom:55
  ports:
   - "10051:10051"
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /etc/timezone:/etc/timezone:ro
   - zbx-prx-data:/usr/lib/zabbix/externalscripts:ro
   - zbx-prx-data:/var/lib/zabbix/modules:ro
   - zbx-prx-data:/var/lib/zabbix/enc:ro
   - zbx-prx-data:/var/lib/zabbix/ssh_keys:ro
   - zbx-prx-data:/var/lib/zabbix/mibs:ro
   - zbx-prx-data:/var/lib/zabbix/snmptraps:rw
  ulimits:
   nproc: 65535
   nofile:
    soft: 20000
    hard: 40000
  environment:
   - ZBX_SERVER_HOST=192.168.0.251;192.168.0.252;192.168.0.253
   - ZBX_HOSTNAME=zbx-prx-swarm
   - DB_SERVER_HOST=mariadb-prx
   - MYSQL_USER=zabbix
   - MYSQL_PASSWORD=zabbix_proxy
   - MYSQL_ROOT_PASSWORD=123qwe.
   - MYSQL_DATABASE=zabbix_proxy
   - ZBX_CACHESIZE=32M
   - ZBX_STARTDBSYNCERS=4
   - ZBX_HISTORYCACHESIZE=16M
   - ZBX_HISTORYINDEXCACHESIZE=4M
   - ZBX_TIMEOUT=30
   - ZBX_PROXYOFFLINEBUFFER=1
   - ZBX_ENABLEREMOTECOMMANDS=1
   - ZBX_DEBUGLEVEL=3
   - ZBX_PROXYLOCALBUFFER=4
   - ZBX_CONFIGFREQUENCY=60
   - ZBX_HOUSEKEEPINGFREQUENCY=12
  depends_on:
   - mariadb-prx
  networks:
   zbx_net_backend:
    aliases:
     - zbx-prx-mysql
   zbx_net_frontend:
  stop_grace_period: 30s
  labels:
   com.zabbix.description: "Zabbix Proxy with MySQL database support"
   com.zabbix.company: "Homelab"
   com.zabbix.component: "zabbix-proxy"
   com.zabbix.dbtype: "mysql"
   com.zabbix.os: "oracle linux"

 mariadb-prx:
  image: mariadb:10.6.14
  ports:
   - "33060:3306"
  command:
   - mysqld
   - --character-set-server=utf8mb4
   - --collation-server=utf8mb4_bin
   - --default-authentication-plugin=mysql_native_password
  volumes:
   - db_data_mariadb:/var/lib/mysql:rw
  environment:
   - MYSQL_USER=zabbix
   - MYSQL_PASSWORD=zabbix
   - MYSQL_ROOT_PASSWORD=123qwe.
  stop_grace_period: 1m
  networks:
   zbx_net_backend:
    aliases:
     - mariadb-prx
   zbx_net_frontend:

volumes:
 db_data_mariadb:
   driver_opts:
     type: "nfs"
     o: "addr=192.168.0.200,nolock,soft,rw"
     device: ":/storage/zabbix-proxy/db"
 zbx-prx-data:
   driver_opts:
     type: "nfs"
     o: "addr=192.168.0.200,nolock,soft,rw"
     device: ":/storage/zabbix-proxy/data"

networks:
  zbx_net_frontend:
    driver: overlay
  zbx_net_backend:
    driver: overlay