services:
 postgres-server:
  image: "${POSTGRESQL_IMAGE}:${POSTGRESQL_IMAGE_TAG}"
  restart: "${RESTART_POLICY}"
  volumes:
   - ${DATA_DIRECTORY}/var/lib/postgresql/data:/var/lib/postgresql/data:rw
  env_file:
   - ${ENV_VARS_DIRECTORY}/.env_db_pgsql
  secrets:
   - POSTGRES_USER
   - POSTGRES_PASSWORD
  stop_grace_period: 1m
  ports:
  - "5432:5432"
  networks:
   frontend:
   database:
    aliases:
     - postgres-server

 db-data-pgsql:
  image: busybox
  volumes:
   - ${DATA_DIRECTORY}/var/lib/postgresql/data:/var/lib/postgresql/data:rw

 elasticsearch:
  image: "${ELASTICSEARCH_IMAGE}:${ELASTICSEARCH_IMAGE_TAG}"
  restart: "${RESTART_POLICY}"
  profiles:
   - elasticsearch
  environment:
   - transport.host=0.0.0.0
   - discovery.zen.minimum_master_nodes=1
  networks:
   database:
    aliases:
     - elasticsearch